import './globals.css'
import Link from 'next/link'
export const metadata = {
  title: 'tets1 ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <header>
      <Link href="/renderData">test </Link>
      </header>
        {children}
      </body>
    </html>
  )
}
